"""
P1 RIGOR FIX 1 — Clopper-Pearson (exact binomial) 95% confidence intervals on every
logical-error-rate (LER) point in the frozen baseline CSVs.

Motivation: a point estimate LER = failures/shots is a
binomial proportion. With rare events (e.g. the [[144,12,12]] code at p=0.02, which has
only ~2 failures in 50,000 shots) the point estimate carries an ENORMOUS relative
uncertainty, and any comparative claim ("beats X", "threshold below Y") that is finer than
the interval width is unsupported. Clopper-Pearson is the exact (conservative) binomial
interval, valid even at 0 successes.

Reads the EXISTING CSVs (does NOT re-run any decode):
    results/exp1/p1_mwpm_baseline.csv     (surface, circuit-level Stim noise)
    results/exp3/p1_qldpc_bposd.csv       (BB, code-capacity noise)
    results/exp3/p1_qldpc_phenom.csv      (BB, phenomenological noise)

Writes (plaintext, next to the sources + a summary in results/):
    <src>_ci.csv       augmented copy with ler_cp_lo / ler_cp_hi / rel_width_pct columns
    results/p1_intervals_summary.txt

Run:
    python p1_intervals.py
"""
from __future__ import annotations
import os, csv
from scipy.stats import beta

# Result directory: repo-root results/ by default; override with $P1_RESULT_DIR.
RESULT_ROOT = os.environ.get(
    "P1_RESULT_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "results"))
EXP1 = os.path.join(RESULT_ROOT, "exp1")
EXP3 = os.path.join(RESULT_ROOT, "exp3")

SOURCES = [
    ("surface / MWPM / circuit-level Stim noise",
     os.path.join(EXP1, "p1_mwpm_baseline.csv"), "distance"),
    ("BB / BP-OSD / code-capacity noise",
     os.path.join(EXP3, "p1_qldpc_bposd.csv"), "code_str"),
    ("BB / BP-OSD / phenomenological noise",
     os.path.join(EXP3, "p1_qldpc_phenom.csv"), "code_str"),
]


def clopper_pearson(fails: int, shots: int, alpha: float = 0.05):
    """Exact binomial (Clopper-Pearson) two-sided CI at confidence 1-alpha.
    Handles the boundary cases fails==0 (lo=0) and fails==shots (hi=1) correctly."""
    if shots == 0:
        return (0.0, 1.0)
    lo = 0.0 if fails == 0 else beta.ppf(alpha / 2.0, fails, shots - fails + 1)
    hi = 1.0 if fails == shots else beta.ppf(1.0 - alpha / 2.0, fails + 1, shots - fails)
    return (float(lo), float(hi))


def fmt(x: float) -> str:
    return f"{x:.4e}"


def process(label: str, path: str, id_col: str, out_lines: list[str]):
    if not os.path.exists(path):
        out_lines.append(f"[MISSING] {path}\n")
        return
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        out_lines.append(f"[EMPTY] {path}\n")
        return

    out_lines.append("=" * 92 + "\n")
    out_lines.append(f"ARM: {label}\n")
    out_lines.append(f"source: {path}\n")
    out_lines.append("-" * 92 + "\n")
    hdr = f"{'id':>14} {'p/other':>10} {'fails':>7} {'shots':>8} {'LER(pt)':>12} " \
          f"{'CP_lo(95%)':>12} {'CP_hi(95%)':>12} {'rel_width':>10}\n"
    out_lines.append(hdr)

    aug = []
    for r in rows:
        fails = int(float(r["failures"]))
        shots = int(float(r["shots"]))
        lo, hi = clopper_pearson(fails, shots)
        pt = fails / shots if shots else 0.0
        # relative CI width vs the point estimate (how many x the point uncertainty is)
        rel = (hi - lo) / pt if pt > 0 else float("inf")
        idv = r.get(id_col, "")
        pv = r.get("p", r.get("distance", ""))
        out_lines.append(
            f"{str(idv):>14} {str(pv):>10} {fails:>7} {shots:>8} {fmt(pt):>12} "
            f"{fmt(lo):>12} {fmt(hi):>12} "
            f"{('inf' if rel == float('inf') else f'{rel*100:8.1f}%'):>10}\n")
        rr = dict(r)
        rr["ler_cp_lo"] = f"{lo:.8e}"
        rr["ler_cp_hi"] = f"{hi:.8e}"
        rr["rel_width_pct"] = ("inf" if rel == float("inf") else f"{rel*100:.2f}")
        aug.append(rr)

    # write augmented CSV next to the source
    out_path = path.replace(".csv", "_ci.csv")
    fieldnames = list(rows[0].keys()) + ["ler_cp_lo", "ler_cp_hi", "rel_width_pct"]
    with open(out_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(aug)
    out_lines.append(f"wrote augmented CSV -> {out_path}\n\n")


def main():
    out_lines = []
    out_lines.append("P1 QEC decoder — Clopper-Pearson 95% binomial confidence intervals\n")
    out_lines.append("(exact two-sided binomial interval per LER point; conservative, valid at 0 events)\n")
    out_lines.append("Generated by p1_intervals.py from the FROZEN baseline CSVs; no decode re-run.\n\n")

    for label, path, idcol in SOURCES:
        process(label, path, idcol, out_lines)

    # --- explicit spotlight on the rare-event [[144,12,12]] p=0.02 point --------------
    out_lines.append("#" * 92 + "\n")
    out_lines.append("RARE-EVENT SPOTLIGHT (the under-resolved bb144 point)\n")
    out_lines.append("#" * 92 + "\n")
    bb144 = os.path.join(EXP3, "p1_qldpc_bposd.csv")
    if os.path.exists(bb144):
        with open(bb144, newline="") as f:
            rows = list(csv.DictReader(f))
        r = next((x for x in rows
                  if x.get("code") == "bb144" and abs(float(x["p"]) - 0.02) < 1e-9), None)
        if r:
            fails = int(float(r["failures"]))
            shots = int(float(r["shots"]))
            lo, hi = clopper_pearson(fails, shots)
            pt = fails / shots
            out_lines.append(
                f"Code [[144,12,12]] (gross code), code-capacity, p = 0.02:\n"
                f"    observed failures      = {fails}\n"
                f"    shots                  = {shots}\n"
                f"    LER point estimate     = {fmt(pt)}   ( = {fails}/{shots} )\n"
                f"    Clopper-Pearson 95% CI = [ {fmt(lo)} , {fmt(hi)} ]\n"
                f"    CI upper/lower ratio   = {hi/lo:.1f}x   (a factor of ~{hi/lo:.0f} of "
                f"multiplicative uncertainty, i.e. ~{__import__('math').log10(hi/lo):.1f} decades)\n"
                f"    interval width         = {fmt(hi-lo)}  "
                f"( {(hi-lo)/pt*100:.0f}% of the point estimate )\n\n")
            out_lines.append(
                "INTERPRETATION / CLAIMS THIS CI CANNOT SUPPORT:\n"
                f"  * With only {fails} logical failures the point LER {fmt(pt)} is essentially "
                "un-resolved: the true LER could plausibly be anywhere in\n"
                f"    [{fmt(lo)}, {fmt(hi)}] at 95% confidence. This is roughly a factor of "
                f"{hi/lo:.0f} between the interval endpoints.\n"
                "  * Any statement of the form \"the [[144,12,12]] LER at p=0.02 is X\" to more "
                "than ~1 significant figure is NOT supported.\n"
                "  * Any decoder-vs-decoder comparison AT THIS POINT (e.g. 'neural beats/matches "
                "BP-OSD at p=0.02 on the gross code') is\n"
                "    UNSUPPORTED unless the competing method's CI is disjoint from this one — a "
                f"gap far larger than {fmt(hi-lo)} would be needed.\n"
                "  * A sub-threshold / distance-scaling claim (bb144 LER << bb72 LER at p=0.02) is "
                "directionally consistent with the point\n"
                "    estimates, but the bb144 CI upper bound must be quoted alongside it; the "
                "SEPARATION should be stated as a bound, not a ratio of point estimates.\n"
                "  * FIX: to resolve this point one needs O(10^6-10^7) shots (rule of thumb: "
                ">=~100 logical failures for a ~10% relative standard error; the 95% CI then spans about -19%/+22%),\n"
                "    OR report it explicitly as an upper bound (LER < CP_hi at 95%) rather than a "
                "point value.\n\n")

    # --- general flags: any point with < 30 failures is under-resolved -----------------
    out_lines.append("=" * 92 + "\n")
    out_lines.append("LOW-COUNT FLAGS (points with < 30 logical failures -> CI too wide for fine claims)\n")
    out_lines.append("=" * 92 + "\n")
    THRESH = 30
    any_flag = False
    for label, path, idcol in SOURCES:
        if not os.path.exists(path):
            continue
        with open(path, newline="") as f:
            rows = list(csv.DictReader(f))
        for r in rows:
            fails = int(float(r["failures"]))
            shots = int(float(r["shots"]))
            if fails < THRESH:
                any_flag = True
                lo, hi = clopper_pearson(fails, shots)
                idv = r.get(idcol, "")
                pv = r.get("p", r.get("distance", ""))
                out_lines.append(
                    f"  [{label}]  {idv} (p/d={pv}): {fails} fails / {shots} shots -> "
                    f"95% CI [{fmt(lo)}, {fmt(hi)}]  "
                    f"(point {fmt(fails/shots) if shots else 'NA'}) -- UNDER-RESOLVED, quote as bound\n")
    if not any_flag:
        out_lines.append("  (none)\n")
    out_lines.append("\nRule of thumb used: >=30 failures for a moderately-tight CI; "
                     ">=~100 for a ~10% relative standard error (95% CI about -19%/+22%).\n")

    text = "".join(out_lines)
    summ = os.path.join(RESULT_ROOT, "p1_intervals_summary.txt")
    with open(summ, "w") as f:
        f.write(text)
    print(text)
    print(f"\nsaved summary -> {summ}")


if __name__ == "__main__":
    main()
